name: build
on: [push, workflow_dispatch]
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash
      - uses: actions/cache@v2
        with:
          path: |
            deps
          key: deps-${{ steps.get-date.outputs.date }}
          restore-keys: |
            deps-
      - run: sudo apt update
      - run: sudo apt install -y cmake ccache
      - uses: hendrikmuhs/ccache-action@v1
      - run: export PATH="/usr/lib/ccache:$PATH"
      - run: cmake .
      - run: make -j$(nproc)
      - uses: actions/upload-artifact@v2
        with:
          name: fisco-bcos
          path: |
            bin/fisco-bcos
