name: FISCO-BCOS GitHub Actions
on: [push, workflow_dispatch]
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update
      - run: sudo apt install -y cmake ccache librocksdb-dev libmicrohttpd-dev libleveldb-dev libsnappy-dev libzdb-dev
      - uses: hendrikmuhs/ccache-action@v1
      - run: export PATH="/usr/lib/ccache:$PATH"
      - run: cmake .
      - run: make -j$(nproc)
      - uses: actions/upload-artifact@v2
        with:
          name: fisco-bcos
          path: |
            bin/fisco-bcos
